language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - mysql -e 'create database loteria_digital;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

dist: precise